/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "d:\\xingkong\\vuepress-theme-xing\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-275af9f9",
    path: "/pages/c80423/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-275af9f9").then(next)
    },
  },
  {
    path: "/pages/c80423/index.html",
    redirect: "/pages/c80423/"
  },
  {
    path: "/01.skill/",
    redirect: "/pages/c80423/"
  },
  {
    name: "v-6016b69c",
    path: "/pages/961b62/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6016b69c").then(next)
    },
  },
  {
    path: "/pages/961b62/index.html",
    redirect: "/pages/961b62/"
  },
  {
    path: "/01.skill/a.html",
    redirect: "/pages/961b62/"
  },
  {
    name: "v-538c6cd0",
    path: "/pages/a9a017/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-538c6cd0").then(next)
    },
  },
  {
    path: "/pages/a9a017/index.html",
    redirect: "/pages/a9a017/"
  },
  {
    path: "/02.exist/02.poorBusy.html",
    redirect: "/pages/a9a017/"
  },
  {
    name: "v-736569b2",
    path: "/pages/473de2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-736569b2").then(next)
    },
  },
  {
    path: "/pages/473de2/index.html",
    redirect: "/pages/473de2/"
  },
  {
    path: "/02.exist/01.homeEducation.html",
    redirect: "/pages/473de2/"
  },
  {
    name: "v-475763d2",
    path: "/pages/05ce71/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-475763d2").then(next)
    },
  },
  {
    path: "/pages/05ce71/index.html",
    redirect: "/pages/05ce71/"
  },
  {
    path: "/02.exist/03.useLess.html",
    redirect: "/pages/05ce71/"
  },
  {
    name: "v-17f13e64",
    path: "/pages/bd5963/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17f13e64").then(next)
    },
  },
  {
    path: "/pages/bd5963/index.html",
    redirect: "/pages/bd5963/"
  },
  {
    path: "/02.exist/04.remoteWork.html",
    redirect: "/pages/bd5963/"
  },
  {
    name: "v-1bb403f2",
    path: "/pages/1e9399/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bb403f2").then(next)
    },
  },
  {
    path: "/pages/1e9399/index.html",
    redirect: "/pages/1e9399/"
  },
  {
    path: "/02.exist/05.tecProgress.html",
    redirect: "/pages/1e9399/"
  },
  {
    name: "v-55407d59",
    path: "/pages/93146c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55407d59").then(next)
    },
  },
  {
    path: "/pages/93146c/index.html",
    redirect: "/pages/93146c/"
  },
  {
    path: "/02.exist/",
    redirect: "/pages/93146c/"
  },
  {
    name: "v-6b62b5aa",
    path: "/pages/604427/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b62b5aa").then(next)
    },
  },
  {
    path: "/pages/604427/index.html",
    redirect: "/pages/604427/"
  },
  {
    path: "/02.exist/06.timeAndMoney.html",
    redirect: "/pages/604427/"
  },
  {
    name: "v-28013ce3",
    path: "/pages/c0a868/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28013ce3").then(next)
    },
  },
  {
    path: "/pages/c0a868/index.html",
    redirect: "/pages/c0a868/"
  },
  {
    path: "/03.readList/",
    redirect: "/pages/c0a868/"
  },
  {
    name: "v-cd05ee50",
    path: "/pages/8f33b0/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd05ee50").then(next)
    },
  },
  {
    path: "/pages/8f33b0/index.html",
    redirect: "/pages/8f33b0/"
  },
  {
    path: "/03.readList/a.html",
    redirect: "/pages/8f33b0/"
  },
  {
    name: "v-aa62f53c",
    path: "/pages/0840ec/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa62f53c").then(next)
    },
  },
  {
    path: "/pages/0840ec/index.html",
    redirect: "/pages/0840ec/"
  },
  {
    path: "/04.website/01.markDown.html",
    redirect: "/pages/0840ec/"
  },
  {
    name: "v-1211de4e",
    path: "/pages/692ee8/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1211de4e").then(next)
    },
  },
  {
    path: "/pages/692ee8/index.html",
    redirect: "/pages/692ee8/"
  },
  {
    path: "/04.website/",
    redirect: "/pages/692ee8/"
  },
  {
    name: "v-6243dfd0",
    path: "/pages/af4787/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6243dfd0").then(next)
    },
  },
  {
    path: "/pages/af4787/index.html",
    redirect: "/pages/af4787/"
  },
  {
    path: "/04.website/a.html",
    redirect: "/pages/af4787/"
  },
  {
    name: "v-422221f9",
    path: "/pages/d2a2d6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-422221f9").then(next)
    },
  },
  {
    path: "/pages/d2a2d6/index.html",
    redirect: "/pages/d2a2d6/"
  },
  {
    path: "/05.about/",
    redirect: "/pages/d2a2d6/"
  },
  {
    name: "v-4f0314d2",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f0314d2").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    name: "v-b130bc9c",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b130bc9c").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-dd4dd15c",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dd4dd15c").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    path: "/@pages/tagsPage.html",
    redirect: "/tags/"
  },
  {
    name: "v-2b4693be",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b4693be").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]