/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Xing's blog",
  "description": "web前端技术博客,专注web前端学习与总结。JavaScript,js,ES6,TypeScript,vue,React,python,css3,html5,Node,git,github等技术文章。",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "前端博客,个人技术博客,前端,前端开发,前端框架,web前端,前端面试题,技术文档,学习,面试,JavaScript,js,ES6,TypeScript,vue,python,css3,html5,Node,git,github,markdown"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#11a8cd"
      }
    ]
  ],
  "pages": [
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/c80423/",
        "categories": [
          "skill"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/01.skill/",
      "relativePath": "01.skill/README.md",
      "key": "v-1b6f3cd0",
      "path": "/pages/c80423/"
    },
    {
      "title": "homeEducation",
      "frontmatter": {
        "title": "homeEducation",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/473de2/",
        "categories": [
          "exist"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/02.exist/01.homeEducation.html",
      "relativePath": "02.exist/01.homeEducation.md",
      "key": "v-6462e80a",
      "path": "/pages/473de2/"
    },
    {
      "title": "poorBusy",
      "frontmatter": {
        "title": "poorBusy",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/a9a017/",
        "categories": [
          "exist"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/02.exist/02.poorBusy.html",
      "relativePath": "02.exist/02.poorBusy.md",
      "key": "v-6b128321",
      "path": "/pages/a9a017/"
    },
    {
      "title": "useLess",
      "frontmatter": {
        "title": "useLess",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/05ce71/",
        "categories": [
          "exist"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/02.exist/03.useLess.html",
      "relativePath": "02.exist/03.useLess.md",
      "key": "v-561a28ca",
      "path": "/pages/05ce71/"
    },
    {
      "title": "tecProgress",
      "frontmatter": {
        "title": "tecProgress",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/1e9399/",
        "categories": [
          "exist"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/02.exist/05.tecProgress.html",
      "relativePath": "02.exist/05.tecProgress.md",
      "key": "v-5e93b2bb",
      "path": "/pages/1e9399/"
    },
    {
      "title": "remoteWork",
      "frontmatter": {
        "title": "remoteWork",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/bd5963/",
        "categories": [
          "exist"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/02.exist/04.remoteWork.html",
      "relativePath": "02.exist/04.remoteWork.md",
      "key": "v-915fe926",
      "path": "/pages/bd5963/"
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/93146c/",
        "categories": [
          "exist"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/02.exist/",
      "relativePath": "02.exist/README.md",
      "key": "v-4954c030",
      "path": "/pages/93146c/"
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/c0a868/",
        "categories": [
          "readList"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/03.readList/",
      "relativePath": "03.readList/README.md",
      "key": "v-f4907b0c",
      "path": "/pages/c0a868/"
    },
    {
      "title": "a",
      "frontmatter": {
        "title": "a",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/8f33b0/",
        "categories": [
          "readList"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/03.readList/a.html",
      "relativePath": "03.readList/a.md",
      "key": "v-1ad193be",
      "path": "/pages/8f33b0/"
    },
    {
      "title": "markDown",
      "frontmatter": {
        "title": "markDown",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/0840ec/",
        "categories": [
          "website"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/04.website/01.markDown.html",
      "relativePath": "04.website/01.markDown.md",
      "key": "v-4a2d526b",
      "path": "/pages/0840ec/",
      "headers": [
        {
          "level": 2,
          "title": "layout: \"xxx\"",
          "slug": "layout-xxx"
        },
        {
          "level": 2,
          "title": "这是二级标题，二级标题底下有横线",
          "slug": "这是二级标题-二级标题底下有横线"
        },
        {
          "level": 3,
          "title": "这是三级标题",
          "slug": "这是三级标题"
        },
        {
          "level": 2,
          "title": "使用3个或者多个“*”的分割线",
          "slug": "使用3个或者多个-的分割线"
        }
      ]
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/692ee8/",
        "categories": [
          "website"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/04.website/",
      "relativePath": "04.website/README.md",
      "key": "v-6ef01030",
      "path": "/pages/692ee8/"
    },
    {
      "title": "a",
      "frontmatter": {
        "title": "a",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/af4787/",
        "categories": [
          "website"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/04.website/a.html",
      "relativePath": "04.website/a.md",
      "key": "v-5604fba1",
      "path": "/pages/af4787/"
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/d2a2d6/",
        "categories": [
          "about"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/05.about/",
      "relativePath": "05.about/README.md",
      "key": "v-363664d0",
      "path": "/pages/d2a2d6/"
    },
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-46c2c6ca",
      "path": "/archives/"
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-4b99781b",
      "path": "/tags/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Xing Kong's blog",
        "tagline": "Web前端技术博客，每天进步一点点。",
        "actionText": "立刻进入 →",
        "actionLink": "/web/",
        "bannerBg": "auto",
        "features": [
          {
            "title": "前端",
            "details": "JavaScript、ES6、Vue框架等前端技术",
            "link": "/web/",
            "imgUrl": "/img/web.png"
          },
          {
            "title": "页面",
            "details": "html(5)/css(3)，前端页面相关技术",
            "link": "/ui/",
            "imgUrl": "/img/ui.png"
          },
          {
            "title": "技术",
            "details": "技术文档、教程、技巧、总结等文章",
            "link": "/technology/",
            "imgUrl": "/img/other.png"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-ca536b72",
      "path": "/"
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-68f81cfb",
      "path": "/categories/"
    },
    {
      "title": "timeAndMoney",
      "frontmatter": {
        "title": "timeAndMoney",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/604427/",
        "categories": [
          "exist"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/02.exist/06.timeAndMoney.html",
      "relativePath": "02.exist/06.timeAndMoney.md",
      "key": "v-7511d633",
      "path": "/pages/604427/"
    },
    {
      "title": "a",
      "frontmatter": {
        "title": "a",
        "date": "2021-12-17T14:59:30.000Z",
        "permalink": "/pages/961b62/",
        "categories": [
          "skill"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/01.skill/a.html",
      "relativePath": "01.skill/a.md",
      "key": "v-5e68bcbb",
      "path": "/pages/961b62/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "技术篇",
        "link": "/skill/",
        "items": [
          {
            "text": "技术文档",
            "link": "/skill/",
            "items": [
              {
                "text": "帮助",
                "link": "/skill/a"
              }
            ]
          }
        ]
      },
      {
        "text": "生活篇",
        "link": "/exist/",
        "items": [
          {
            "text": "穷忙的人生",
            "link": "/exist/02.poorBusy"
          },
          {
            "text": "那些无用的人",
            "link": "/exist/03.useLess"
          },
          {
            "text": "技术的进步迫使暴力犯罪越来越少",
            "link": "/exist/05.tecProgress"
          },
          {
            "text": "长大后自卑的孩子，大多出自这几种家庭，别不当回事",
            "link": "/exist/01.homeEducation"
          },
          {
            "text": "能用钱解决的问题，不要花宝贵的时间",
            "link": "/exist/06.timeAndMoney"
          },
          {
            "text": "办公室主导的工作场所将在十年内结束",
            "link": "/exist/04.remoteWork"
          }
        ]
      },
      {
        "text": "读书清单",
        "link": "/readList/",
        "items": [
          {
            "text": "技术文档",
            "link": "readList/a"
          }
        ]
      },
      {
        "text": "网站",
        "link": "/more/",
        "items": [
          {
            "text": "学习",
            "link": "website/a"
          },
          {
            "text": "markDown",
            "link": "/website/markDown"
          }
        ]
      },
      {
        "text": "CSDN",
        "link": "https://blog.csdn.net/qq_35876316?type=blog"
      },
      {
        "text": "关于",
        "link": "/about/"
      },
      {
        "text": "Github",
        "link": "https://github.com/fdliu/lzx-vuepress"
      }
    ],
    "sidebarDepth": 2,
    "logo": "/img/logo.png",
    "searchMaxSuggestions": 10,
    "lastUpdated": "上次更新",
    "docsDir": "docs",
    "editLinks": true,
    "editLinkText": "编辑",
    "bodyBgImg": [
      "https://cdn.jsdelivr.net/gh/xugaoyi/image_store/blog/20200507175828.jpeg",
      "https://cdn.jsdelivr.net/gh/xugaoyi/image_store/blog/20200507175845.jpeg",
      "https://cdn.jsdelivr.net/gh/xugaoyi/image_store/blog/20200507175846.jpeg"
    ],
    "bodyBgImgOpacity": 0.5,
    "pageButton": false,
    "sidebar": {
      "/02.exist/": [
        [
          "01.homeEducation.md",
          "homeEducation",
          "/pages/473de2/"
        ],
        [
          "02.poorBusy.md",
          "poorBusy",
          "/pages/a9a017/"
        ],
        [
          "03.useLess.md",
          "useLess",
          "/pages/05ce71/"
        ],
        [
          "04.remoteWork.md",
          "remoteWork",
          "/pages/bd5963/"
        ],
        [
          "05.tecProgress.md",
          "tecProgress",
          "/pages/1e9399/"
        ],
        [
          "06.timeAndMoney.md",
          "timeAndMoney",
          "/pages/604427/"
        ]
      ],
      "catalogue": {},
      "/04.website/": [
        [
          "01.markDown.md",
          "markDown",
          "/pages/0840ec/"
        ]
      ]
    },
    "blogger": {
      "avatar": "https://cdn.jsdelivr.net/gh/xugaoyi/image_store/blog/20200103123203.jpg",
      "name": "Xing Kong",
      "slogan": "一个萝卜"
    },
    "social": {
      "icons": [
        {
          "iconClass": "icon-youjian",
          "title": "发邮件",
          "link": "mailto:894072666@qq.com"
        },
        {
          "iconClass": "icon-github",
          "title": "GitHub",
          "link": "https://github.com/fdliu"
        },
        {
          "iconClass": "icon-erji",
          "title": "听音乐",
          "link": ""
        }
      ]
    },
    "footer": {
      "createYear": 2021,
      "copyrightInfo": "Xing Kong| <a href=\"https://github.com/fdliu/vuepress-theme-xing/\" target=\"_blank\">MIT License</a>"
    }
  }
}